language: php
php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5

env:
  - DB=mysql
  - DB=postgres

before_script:
  # MUST UPDATE THIS FOR YOUR EXTENSION
  - VENDOR="phpbb"
  - NAME="example"
  
  # clone phpBB
  - git clone "git://github.com/phpbb-extensions/test-framework.git" "./../../test-framework"
  
  # run the travis.yml file from the cloned repo to finish the setup
  - ./../../test-framework/.travis.yml
